# Generated by Django 4.2.6 on 2023-10-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('humedad', models.IntegerField()),
                ('id_nodo', models.IntegerField()),
                ('id_sensor', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
