# Generated by Django 4.2.6 on 2023-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mediciones_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediciones',
            name='humedad',
            field=models.FloatField(),
        ),
    ]
